insert into artifacts (id, country, description, filename, product_base_notes, product_middle_notes, product_top_notes, artifact_gender, artifact_title, artifacter, price, type, volume, year) values (1, 'Germany', null, 'sphere_of_annihilation.jpg', 'annihilation', '', '', 'unknown', '', '', 35, '', '100', 2010);
insert into artifacts (id, country, description, filename, product_base_notes, product_middle_notes, product_top_notes, artifact_gender, artifact_title, artifacter, price, type, volume, year) values (2, 'Germany', null, 'Arnd.PNG', 'Arnd', '', '', 'unknown', '', '', 21, '', '75', 1995);
insert into artifacts (id, country, description, filename, product_base_notes, product_middle_notes, product_top_notes, artifact_gender, artifact_title, artifacter, price, type, volume, year) values (3, 'Germany', null, 'crenshinibon.jpg', 'crenshinibon', '', '', 'unknown', '', '', 45, '', '100', 2015);
insert into artifacts (id, country, description, filename, product_base_notes, product_middle_notes, product_top_notes, artifact_gender, artifact_title, artifacter, price, type, volume, year) values (4, 'Germany', null, 'crown_of_horns.jpg', 'Crown Of Horns', '', '', 'unknown', '', '', 26, '', '90', 2000);
insert into artifacts (id, country, description, filename, product_base_notes, product_middle_notes, product_top_notes, artifact_gender, artifact_title, artifacter, price, type, volume, year) values (5, 'Germany', null, 'cyrinishad.jpg', 'Cyric', '', '', 'unknown', '', '', 27, '', '90', 2001);
insert into artifacts (id, country, description, filename, product_base_notes, product_middle_notes, product_top_notes, artifact_gender, artifact_title, artifacter, price, type, volume, year) values (6, 'Germany', null, 'deck_of_many_things.jpg', 'Deck of many things', '', '', 'unknown', '', '', 47, '', '100', 2016);
insert into artifacts (id, country, description, filename, product_base_notes, product_middle_notes, product_top_notes, artifact_gender, artifact_title, artifacter, price, type, volume, year) values (7, 'Spain', null, 'Dorian-Gray.jpg', 'Gray', '', '', 'unknown', '', '', 76, '', '100', 2019);
insert into artifacts (id, country, description, filename, product_base_notes, product_middle_notes, product_top_notes, artifact_gender, artifact_title, artifacter, price, type, volume, year) values (27, 'Spain', null, 'orbs_of_dragonkind.jpg', 'Dragon Orbs', '', '', 'unknown', '', '', 156, '', '150', 2016);
insert into artifacts (id, country, description, filename, product_base_notes, product_middle_notes, product_top_notes, artifact_gender, artifact_title, artifacter, price, type, volume, year) values (28, 'France', null, 'eye_and_hand_of_vecna.jpg', 'Vecna', '', '', 'unknown', '', '', 85, '', '100', 2004);
insert into artifacts (id, country, description, filename, product_base_notes, product_middle_notes, product_top_notes, artifact_gender, artifact_title, artifacter, price, type, volume, year) values (29, 'France', null, 'Magi.PNG', 'Magi', '', '', 'unknown', '', '', 88, '', '100', 2014);
insert into artifacts (id, country, description, filename, product_base_notes, product_middle_notes, product_top_notes, artifact_gender, artifact_title, artifacter, price, type, volume, year) values (30, 'France', null, 'mythallar.jpg', 'Myth', '', '', 'unknown', '', '', 70, '', '100', 1993);
insert into artifacts (id, country, description, filename, product_base_notes, product_middle_notes, product_top_notes, artifact_gender, artifact_title, artifacter, price, type, volume, year) values (31, 'France', null, 'nether_scrolls.PNG', 'nether', '', '', 'unknown', '', '', 90, '', '100', 2007);
insert into artifacts (id, country, description, filename, product_base_notes, product_middle_notes, product_top_notes, artifact_gender, artifact_title, artifacter, price, type, volume, year) values (32, 'France', null, 'talisman_of_pure_good_ultimate_evil.jpg', 'pure good', '', '', 'unknown', '', '', 104, '', '100', 2019);
insert into artifacts (id, country, description, filename, product_base_notes, product_middle_notes, product_top_notes, artifact_gender, artifact_title, artifacter, price, type, volume, year) values (33, 'France', null, 'regalia_of_might.jpg', 'might', '', '', 'unknown', '', '', 192, '', '200', 1921);
insert into artifacts (id, country, description, filename, product_base_notes, product_middle_notes, product_top_notes, artifact_gender, artifact_title, artifacter, price, type, volume, year) values (34, 'France', null, 'ring_of_winter.jpg', 'winter', '', '', 'unknown', '', '', 152, '', '100', 2010);
insert into artifacts (id, country, description, filename, product_base_notes, product_middle_notes, product_top_notes, artifact_gender, artifact_title, artifacter, price, type, volume, year) values (35, 'France', null, 'rod_of_seven_parts.jpg', 'rod', '', '', 'unknown', '', '', 110, '', '100', 1987);
insert into artifacts (id, country, description, filename, product_base_notes, product_middle_notes, product_top_notes, artifact_gender, artifact_title, artifacter, price, type, volume, year) values (36, 'France', null, 'scepter-that-looks-like-a-Reglia-of-Good.jpg', 'Regalia', '', '', '', '', 97, '', '100', 2004);
insert into artifacts (id, country, description, filename, product_base_notes, product_middle_notes, product_top_notes, artifact_gender, artifact_title, artifacter, price, type, volume, year) values (37, 'France', null, 'philosophers_stone.jpg', 'stone', '', '', 'unknown', '', '', 100, '', '75', 2009);
insert into artifacts (id, country, description, filename, product_base_notes, product_middle_notes, product_top_notes, artifact_gender, artifact_title, artifacter, price, type, volume, year) values (38, 'France', null, 'SwordOfKas.PNG', 'Kas', '', ', ', 'unknown', '', '', 141, '', '75', 2016);
insert into artifacts (id, country, description, filename, product_base_notes, product_middle_notes, product_top_notes, artifact_gender, artifact_title, artifacter, price, type, volume, year) values (39, 'France', null, 'Talisman.PNG', 'Talisman', '', '', 'unknown', '', '', 89, '', '75', 2008);
insert into artifacts (id, country, description, filename, product_base_notes, product_middle_notes, product_top_notes, artifact_gender, artifact_title, artifacter, price, type, volume, year) values (40, 'France', null, 'third_imaskarcana.jpg', 'Third', '', '', 'unknown', '', '', 94, '', '75', 2005);
insert into artifacts (id, country, description, filename, product_base_notes, product_middle_notes, product_top_notes, artifact_gender, artifact_title, artifacter, price, type, volume, year) values (41, 'France', null, 'wand_of_orcus.jpg', 'Wand', ' ', ' ', 'unknown', ' ', 62, ' ', '100', 1988);



