create sequence artifact_id_seq start 109 increment 1;
create sequence users_id_seq start 4 increment 1;
create sequence order_item_seq start 12 increment 1;
create sequence orders_seq start 6 increment 1;

create table orders
(
    id           int8 generated by default as identity,
    address      varchar(255) ,
    city         varchar(255) ,
    date         timestamp default current_timestamp,
    email        varchar(255) ,
    first_name   varchar(255) ,
    last_name    varchar(255) ,
    phone_number varchar(255) ,
    post_index   int4 ,
    total_price  float8 ,
    user_id      int8,
    primary key (id)
);
create table orders_artifacts
(
    order_id    int8 not null,
    artifacts_id int8 not null
);
create table artifacts
(
    id                     int8 not null,
    country                varchar(255) not null,
    description            varchar(1000),
    filename               varchar(255),
    product_base_notes   varchar(255) ,
    product_middle_notes varchar(255),
    product_top_notes    varchar(255),
    artifact_gender         varchar(255),
    artifact_title          varchar(255) ,
    artifacter               varchar(255),
    price                  int4,
    type                   varchar(255) ,
    volume                 varchar(255),
    year                   int4 ,
    primary key (id)
);
create table user_role
(
    user_id int8 not null,
    roles   varchar(255)
);
create table users
(
    id                  int8    not null,
    activation_code     varchar(255),
    active              boolean ,
    address             varchar(255),
    city                varchar(255),
    email               varchar(255),
    first_name          varchar(255),
    last_name           varchar(255),
    password            varchar(255),
    password_reset_code varchar(255),
    phone_number        varchar(255),
    post_index          varchar(255),
    primary key (id)
);
create table users_artifact_list
(
    user_id         int8 not null,
    artifact_list_id int8 not null
);
alter table if exists orders
    add constraint FK32ql8ubntj5uh44ph9659tiih foreign key (user_id) references users;
alter table if exists orders_artifact
    add constraint FK9c3l5vucp0yrrwpc0v8vk8knt foreign key (artifacts_id) references artifacts;
alter table if exists orders_artifacts
    add constraint FK8jft4d30d5dgvauht7ssndwau foreign key (order_id) references orders;
alter table if exists user_role
    add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users;
alter table if exists users_artifact_list
    add constraint FK9neiuundys2yde15o8tcybbvw foreign key (artifact_list_id) references artifacts;
alter table if exists users_artifact_list
    add constraint FKsnhp8qv0xdtp17dmdrhq201ym foreign key (user_id) references users;
